### ISSUE TITLE
attach spans to the request span

### ISSUE THREAD

**Issue by RoadRunnr** [beam-telemetry/cowboy_telemetry#12]
The REAME says:

> The telemetry handlers are executed from the cowboy connection process, not from the request process.

That mean the request process has no access to the span context. How am I then supposed to add subspans to the request span?

**Comment by RoadRunnr** [comment]
found it, would be nice to add this to the doc.

In the request handler, do this to restore the opentelemetry context:
```
    Ctx = opentelemetry_process_propagator:fetch_parent_ctx(),
    otel_ctx:attach(Ctx),
```

**Comment by josevalim** [comment]
This is specific to open telemetry, but I bet a pull request for docs there would be welcome.
