### ISSUE TITLE
Relax dependency on Telemetry

### ISSUE THREAD

**Issue by eldano** [beam-telemetry/cowboy_telemetry#14]
Would it be possible to relax the dependency on telemetry?
Right now the dependency is marked as (~> 1.0), however seeing the changelog on telemetry there are no changes between 0.4.3 and 1.0.0, so in order to make upgrades easier it would be nice if the requirements for this library admitted also 0.4.3.
I can open a PR if we're good with that.

**Comment by josevalim** [comment]
I think that's backwards. :) You should rather ask for libs that require only v0.4.3 to support v1.0.0 too!

Meanwhile, you can go with {:telemetry, "~> 1.0.0", override: true} in your mix.exs. :)

Thanks for pinging though!

**Comment by eldano** [comment]
Yeah that makes sense too. However there's no reason to ask for 1.0 if this
library also works with earlier versions, I see a lot of libraries that
depend on telemetry that set the dependency as either ~> 0.4 or ~> 1.0
